title: 9gr
description: The Site of FunctionalMetatable (9gr)
baseurl: "beta"
url: https://FunctionalMetatable.github.io

author: FunctionalMetatable
copyright_year: 2021
repository: https://github.com/FunctionalMetatable/beta

markdown: kramdown
