title: 9gr
description: The Site of FunctionalMetatable (9gr)
baseurl: ""
url: https://FunctionalMetatable.github.io

author: FunctionalMetatable
copyright_year: 2021
repository: https://github.com/FunctionalMetatable/beta
logoUrl: https://cdn2.scratch.mit.edu/get_image/user/71379194_500x500.png

markdown: kramdown

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-minifier
  - jekyll-archives
  - jekyll-git_metadata
