name: Deploy Site
on: [ push ]

jobs:
   deploy:
       runs-on: ubuntu-latest
       
       steps:
         - name: Checkout
           uses: actions/checkout@master

     
         - name: Setup Node.js
           uses: actions/setup-node@v2.1.2
           with:
              node_version: 14.x
      
         - name: Install Dependencies
           run: |
               cd src
               yarn install

         - name: Generate Site
           run: yarn run generate

         - name: Deploy to GitHub Pages
           uses: peaceiris/actions-gh-pages@v3
           with:
              github_token: ${{ secrets.GITHUB_TOKEN }}
              publish_dir: ./dist
       
         - run: echo Finished Build
